### ISSUE TITLE
Update the footer immediately 

### ISSUE THREAD

**Issue by kirankrish792** [NoSineB/nosineb.github.io#4]
(@hafiscp ) Kindly update the footer section, to ( Made with ❤️ By  IEEE SB CEV WEB TEAM )
<img width="1459" alt="Screenshot 2024-04-08 at 8 20 58 PM" src="https://github.com/NoSineB/nosineb.github.io/assets/64974499/37ec79d3-082e-473d-bebe-226acd55cd59">

**Comment by hafiscp** [comment]
I'll look into it.

**Comment by NoSineB** [comment]
![Screenshot 2024-04-08 204700](https://github.com/NoSineB/nosineb.github.io/assets/132141781/f93b6c4c-536b-44af-918e-1a2917e4328a)
Updated
